### PR TITLE
fix: v1compat and auth schemes

### PR DESCRIPTION
**Pull request by jstirnaman**
* Fixes auth (security) schemes in cloud, oss, and v1compat.
* Adds missing `db=` and `rp=` query params in v1compat `/query`.
* Adds tagging for navigation in v1compat API docs.

### CODE REVIEW

**Comment by jstirnaman** [comment]
Cloud and OSS `/api/v2/me/password`, `/api/v2/users/{userID}/password`, and `/api/v2/signin` paths reference securityScheme `BasicAuthentication`, meaning those APIs support Basic auth. Is that correct?

**Review by glinton — APPROVED** [review]
Looks fine, don't forget to run `make generate-all` before committing to clear up that test :slightly_smiling_face:

**Comment by wbaker85** [comment]
For OSS, `/api/v2/signin` does use `BasicAuthentication` to create a session from the provided user name/password.

`/api/v2/me/password` does not work at all. It's just implemented in a way such that it could never work correctly. I think we should actually eliminate this route from the API spec as `/api/v2/users/{userID}/password` is the correct endpoint to use for this, and is what the CLI uses. I don't think these endpoints are used on cloud for user management currently unless @glinton knows otherwise?

`/api/v2/users/{userID}/password` actually uses token authentication like everything else. The user ID comes from the URL and the request body contains a `password` field that the user's password will be updated to if the token has the correct permissions.

**Comment by jstirnaman** [comment]
@wbaker85 Thanks for looking into this and explaining. I'll create some issues and fix what I can.

**Pull request merged**
