### PR TITLE
chore: update clusters contract

### PR DESCRIPTION
**Pull request by subirjolly**
a few properties of `Cluster` entity need to be `boolean` instead of `string`.

### CODE REVIEW

**Review by eatondustin1 — APPROVED** [review]
Looks good, nice catch!

**Review by abshierjoel — APPROVED** [review]
This looks good to me. We're already treating these as `boolean` and `number` types in quartz, so this shouldn't make any conflict 🥳

**Comment by wdoconnell** [comment]
Thanks all!

**Review by randycoulman — APPROVED** [review]
This looks right to me. Sorry we got this so wrong :-(.

**Pull request merged**
