### PR TITLE
fix: repair code fence backticks in descriptions

### LINKED ISSUE #540: documentation: the opening backtick for a code fence must appear at the start of the line
When running a code generation tool (@influxdata/oats v 0.7.0), it reports wrong documentation contrent, 

***3 backticks  must appear at start of the line***

```
/influxdb-client-js/packages/apis/src/generated/types.ts
  1931:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  1940:36  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  1940:45  warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  1940:48  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  1940:57  warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  1940:58  warning  tsdoc-at-sign-in-word: The "@" character looks like part of a TSDoc tag; use a backslash to escape it                       tsdoc/syntax
  1943:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  1948:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  1949:3   warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  1951:16  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  1954:5   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  1956:3   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  1957:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  2017:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  2018:3   warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  2018:13  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  2020:26  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  2023:9   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  2024:5   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  2025:3   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  2026:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  2030:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
  2031:3   warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  2031:13  warning  tsdoc-malformed-inline-tag: Expecting a TSDoc tag starting with "{@"                                                        tsdoc/syntax
  2034:50  warning  tsdoc-unnecessary-backslash: A backslash can only be used to escape a punctuation character                                 tsdoc/syntax
  2034:52  warning  tsdoc-unnecessary-backslash: A backslash can only be used to escape a punctuation character                                 tsdoc/syntax
  2037:5   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  2038:3   warning  tsdoc-escape-right-brace: The "}" character should be escaped using a backslash to avoid confusion with a TSDoc inline tag  tsdoc/syntax
  2039:3   warning  tsdoc-code-fence-opening-indent: The opening backtick for a code fence must appear at the start of the line                 tsdoc/syntax
```

More specifically, the following types from oss.yml contains such backticks that are not aligned with the start of the line.
* TemplateApply / secrets (4-times)
* Template / spec (4-times)

### PR DESCRIPTION
**Pull request by sranka**
Fixes #540 

It repairs 2 src/common/schemas type descriptions to have code fence backticks at the start of the line and regenerates the rest. There are then no warnings when running `oats` typescript code generator on the modified `oss.yml`.

Note also that the code generated in InfluxDB clients (from swagger) will not understand the intention of backtick Markdown code blocks. Anyway, I also had to repair these backticks in an extra post-processing step in influxdb-client-js using a custom node script.

### CODE REVIEW

**Comment by sranka** [comment]
@jstirnaman please take a look, I repaired the parts that you created/changed.

**Comment by sranka** [comment]
FYI: the code generated in InfluxDB clients will not understand the intention of backtick Markdown code blocks.

**Review by jstirnaman — APPROVED** [review]
Thanks @sranka. I also verified your fix in `docs-v2/api-docs`.

**Comment by jstirnaman** [comment]
> FYI: the code generated in InfluxDB clients will not understand the intention of backtick Markdown code blocks.

@sranka Can you elaborate on this: is it causing a problem or not rendered or...?

**Comment by sranka** [comment]
> @sranka Can you elaborate on this: is it causing a problem or not rendered or...?

Even though swagger/openapi allows to use Markdown in descriptions, the existing code generators (from swagger to a specific programming language) do not implement any translation logic to convert markdown text to what is expected in a given language. The tripple-backtick code markdown block that was used herein as an example
- is understood by python `pdoc3` API documentation generator (was wrong, repaired in this PR)
- requires extra pre-processing in javascript client, because the javascript build tools wrongly indent the code blocks that are then not recognized by typescript api-documenter
- is not understood in java (`<pre>{@code ...}</pre>` is used)
- is not understood in c# (`<code></code>` is used)
- is not understood in ruby (`=begin =end` is used)
- ... other apidoc generators might not render description elements at all

The tripple backticks probably have no meaning when they are not understood  ... they appear in the generated code, but the code block can lose indentantion and it could be merged to appear as a continuous text in a paragraph.

**Comment by jstirnaman** [comment]
> > @sranka Can you elaborate on this: is it causing a problem or not rendered or...?
> 
> Even though swagger/openapi allows to use Markdown in descriptions, the existing code generators (from swagger to a specific programming language) do not implement any translation logic to convert markdown text to what is expected in a given language. The tripple-backtick code markdown block that was used herein as an example
> 
> * is understood by python `pdoc3` API documentation generator (was wrong, repaired in this PR)
> * requires extra pre-processing in javascript client, because the javascript build tools wrongly indent the code blocks that are then not recognized by typescript api-documenter
> * is not understood in java (`<pre>{@code ...}</pre>` is used)
> * is not understood in c# (`<code></code>` is used)
> * is not understood in ruby (`=begin =end` is used)
> * ... other apidoc generators might not render description elements at all
> 
> The tripple backticks probably have no meaning when they are not understood ... they appear in the generated code, but the code block can lose indentantion and it could be merged to appear as a continuous text in a paragraph.

Thanks for the detailed explanation. @sunbryely-influxdata and I will move code samples from `description` elements to elements defined for examples (`example`, `examples`, and `x-codeSample`) and reserve future samples to those elements.

**Pull request merged**
